const translations = {
  ru: {
// Шапка ru
    homehed: "Главная",
    producthed: "Продукты",
    contacthed: "Контакты",
    abouthed: "О нас",
    contactcallhed: "Связаться с нами",
// Страница Главная ru
    heroTitle: "СКЛАД ИНФОРМАЦИОННЫХ ТЕХНОЛОГИЙ",
    heroText: "Команда специалистов в области проектирования, BIM-моделирования и информационной безопасности. Оказываем услуги по продаже лицензионных программ для моделирования и антивирусов, помогаем с настройкой и обучением, обеспечиваем поддержку клиентов.",
    heroBtnProducts: "Наши продукты",
    heroBtnLearnMore: "Узнать больше",

    whyChooseUs: "Почему выбирают СИТ?",
    whyChooseDesc: "Наши решения обеспечивают мощную защиту и высокую производительность.",
    advantage1: "Современная защита",
    advantage1Desc: "От вирусов, программ-вымогателей и угроз нулевого дня.",
    advantage2: "Быстрая работа",
    advantage2Desc: "Низкая нагрузка на систему, высокая эффективность.",
    advantage3: "Конфиденциальность",
    advantage3Desc: "Ваши данные всегда под защитой.",
    advantage4: "Круглосуточная поддержка",
    advantage4Desc: "Мы всегда рядом, когда это нужно.",

    ourProducts: "Наши продукты",
    ourProductsDesc: "Ознакомьтесь с нашими ключевыми решениями: лицензионные программы для BIM-моделирования и проектирования, а также современные антивирусные решения для защиты ваших устройств и данных.",
    viewAllProducts: "Посмотреть все продукты",

    reviewsTitle: "Нам доверяют миллионы",

    ctaTitle: "Готовы защитить свой цифровой мир?",
    ctaText: "Станьте частью защищённого цифрового мира вместе с СИТ.",
    ctaBtnStart: "Начать",
    ctaBtnContact: "Связаться с отделом продаж",

    awardsTitle: "Награды и достижения",
    awardsDesc: "Склад Информационных Технологий — ведущий поставщик программных решений для проектирования и информационного моделирования, а также надежных продуктов по кибербезопасности. Компания отмечена отраслевыми наградами за внедрение инновационных решений в области BIM и защиты данных.",
    award1: "Лучший антивирус 2025",
    award2: "Топ-провайдер безопасности",
    award3: "Выбор клиентов",
    award4: "Сертифицированная защита",

    // Страница Продукты ru
    productTitle: "Наши продукты",
    productDesc: "Предлагаем лицензионные программные продукты для проектирования, BIM-моделирования и инженерных задач, а также обучающие курсы для специалистов.",
    searchPlaceholder: "Поиск продуктов...",
    filters: "Фильтры",
    price: "Цена (₸):",
    from: "От",
    to: "До",
    categories: "Категории:",
    cat1: "Autodesk",
    cat2: "Kaspersky lab",
    cat3: "Защита данных",
    apply: "Применить",
    reset: "Сбросить фильтр",
    more: "Подробнее",

    prod1desc: "Решение для проектирования объектов инфраструктуры.",
    prod2desc: "Проверка архитектурных проектов.",
    prod3desc: "Защита ПК, серверов и мобильных устройств.",
    prod4desc: "BIM для проектировщиков зданий и инженеров.",
    prod5desc: "3D-моделирование, анимация и рендеринг.",
    prod6desc: "3D-моделирование для BIM-проектов и визуализации.",

    // Страница Контакты ru
    contactTitle: "Свяжитесь с нами",
    contactDesc1: "Если у вас есть вопросы по продуктам или услугам,",
    contactDesc2: "наша команда всегда готова помочь.",
    ourContacts: "Наши контакты",
    contactText: "Мы здесь, чтобы помочь с любыми вопросами о наших продуктах, ценах или решениях безопасности. Свяжитесь с нами по любому из способов ниже, и мы ответим как можно быстрее.",
    phone: "Телефон",
    email: "Email",
    office: "Офис",
    workTime: "График работы",
    socialTitle: "Мы в соцсетях",
    formTitle: "Отправить сообщение",
    nameLabel: "Ваше имя *",
    phoneLabel: "Телефон",
    emailLabel: "Email *",
    subjectLabel: "Тема *",
    subjectOption: "Выберите тему",
    subject1: "Вопрос по продукту",
    subject2: "Техническая поддержка",
    subject3: "Оплата и биллинг",
    subject4: "Партнерство",
    subject5: "Другое",
    messageLabel: "Сообщение *",
    messagePlaceholder: "Как мы можем вам помочь?",
    agree: "Я согласен с",
    policy: "политикой конфиденциальности",
    sendBtn: "Отправить",
    thanksText: "Спасибо, ваша заявка была отправлена!",
    howFindUs: "Как нас найти",
    addressFooter: "ул. Луговая, 16, офис 116, Павлодар, Казахстан",
    workTime1: "Пн-Пт: 9:00–18:00",
    workTime2: "Пн-Пт: 09:00–18:00",
    weekend: "Сб-Вс: Выходной",

    // Страница О нас ru
    aboutTitle: "Склад Информационных Технологий",
    aboutSubtitle: "14 ЛЕТ НАДЕЖНОСТЬ, ПРОВЕРЕННАЯ ВРЕМЕНЕМ.",
    aboutHeader: "О компании",
    aboutDesc: "Склад информационных технологий - это команда высококлассных специалистов с практическим опытом работы в сфере BIM-моделирования и внедрения ВIM.",
    missionTitle: "Наша миссия",
    missionDesc1: "Склад информационных технологий является авторизованным поставщиком решений Autodesk и интегратором в области BIM-технологий, а также предоставляет услуги квалифицированного обучения в области BIM для проектировщиков, BIM-менеджеров и руководителей.",
    missionDesc2: "Своим клиентам мы предлагаем не отдельные продукты, а комплексные решения по следующим направлениям:",
    missionPoint1: "1. Внедрение инновационных инструментов проектирования.",
    missionPoint2: "2. Информационная безопасность.",
    missionPoint3: "3. Антивирусная безопасность.",
    missionPoint4: "4. Решение не стандартных IT задач.",
    valuesTitle: "Наши основные ценности",
    valuesDesc: "Принципы, которые лежат в основе нашей работы в компании СИТ.",
    value1: "Безопасность без компромиссов",
    value1desc: "Мы никогда не идем на уступки в вопросах безопасности. Наши решения созданы с многослойной защитой для полной безопасности от любых угроз.",
    value2: "Клиенты на первом месте",
    value2desc: "Мы разрабатываем продукты, исходя из потребностей наших пользователей, делая кибербезопасность доступной и удобной для каждого.",
    value3: "Постоянные инновации",
    value3desc: "Угрозы эволюционируют, и мы тоже. Мы активно инвестируем в исследования и разработки, чтобы быть на шаг впереди.",
    value4: "Глобальный взгляд",
    value4desc: "С командами по всему миру мы предлагаем разнообразные взгляды на кибербезопасность и решаем проблемы, актуальные в разных регионах.",
    value5: "Стремление к совершенству",
    value5desc: "Мы придерживаемся самых высоких стандартов во всем: от разработки продуктов до поддержки клиентов.",
    value6: "Образование и обучение",
    value6desc: "Мы верим в силу знаний и делаем всё возможное для повышения кибер-грамотности и распространения полезной информации.",
    teamTitle: "Наша команда",
    teamDesc: "Познакомьтесь с профессионалами, которые стоят за успехом нашей компании.",
    journeyTitle: "Наш путь",
    journeyDesc: "С момента основания и по сей день мы посвятили себя развитию цифровой безопасности.",
    year2011: "Начало",
    year2011desc: "ТОО Склад информационных технологий был основан командой экспертов по безопасности.",
    year2013: "Расширение",
    year2013desc: "Мы добавили мобильную защиту и открыли первый международный офис в Павлодаре.",
    year2016: "Награда за инновации",
    year2016desc: "Наша технология на базе ИИ получила глобальную премию за инновации в безопасности. Мы достигли 5 миллионов пользователей по всему миру.",
    year2019: "Глобальное присутствие",
    year2019desc: "Открытие офисов в Токио, Сингапуре и Сан-Паулу расширило наше присутствие до 12 стран.",
    year2022: "Бизнес-решения",
    year2022desc: "Мы запустили платформу для корпоративной защиты, обеспечивая безопасность бизнесов любого масштаба.",
    year2025: "Сегодня",
    year2025desc: "Мы защищаем более 20 миллионов пользователей и продолжаем развиваться, используя ИИ и машинное обучение для новых решений в сфере безопасности.",
    ctaTitle: "Присоединяйтесь к нашей миссии по защите цифрового мира",
    ctaDesc: "Почувствуйте спокойствие с нашими решениями, которым доверяют миллионы.",
    ctaProductBtn: "Изучить продукты",
    ctaContactBtn: "Связаться с нами",

    // Футер ru
    footerCompanyDesc: "Склад Информационных Технологий — ваш надежный партнер в сфере информационной безопасности.",
    footerProductsTitle: "Наши продукты",
    footerWorkTitle: "График работы",
    footerContactTitle: "Контакты",
    footerProduct1: "Autodesk",
    footerProduct2: "Kaspersky Lab",
    footerProduct3: "Обучающие курсы",
    footerProduct4: "Оптимизация системы",
    footerProduct5: "Защищенный браузер",
    footerWorkMon: "Понедельник: 09:00–18:00 (обед 13:00–14:00)",
    footerWorkTue: "Вторник: 09:00–18:00 (обед 13:00–14:00)",
    footerWorkWed: "Среда: 09:00–18:00 (обед 13:00–14:00)",
    footerWorkThu: "Четверг: 09:00–18:00 (обед 13:00–14:00)",
    footerWorkFri: "Пятница: 09:00–18:00 (обед 13:00–14:00)",
    footerWorkSat: "Суббота: Выходной",
    footerWorkSun: "Воскресенье: Выходной",
    footerAddress: "Луговая, 16, офис 116, Павлодар, Казахстан",
    footerCopyright: "© 2025 ТОО Склад Информационных Технологий. Все права защищены."
  },

  en: {
// Шапка en
    homehed: "Home",
    producthed: "Products",
    contacthed: "Contacts",
    abouthed: "About Us",
    contactcallhed: "Contact Us",
// Страница Главная en
    heroTitle: "INFORMATION TECHNOLOGY WAREHOUSE",
    heroText: "A team of specialists in design, BIM modeling and cybersecurity. We provide licensed software for modeling and antivirus protection, assist with setup and training, and provide customer support.",
    heroBtnProducts: "Our Products",
    heroBtnLearnMore: "Learn More",

    whyChooseUs: "Why Choose SIT?",
    whyChooseDesc: "Our solutions ensure strong protection and high performance.",
    advantage1: "Modern Protection",
    advantage1Desc: "From viruses, ransomware, and zero-day threats.",
    advantage2: "High Speed",
    advantage2Desc: "Low system load, high efficiency.",
    advantage3: "Confidentiality",
    advantage3Desc: "Your data is always protected.",
    advantage4: "24/7 Support",
    advantage4Desc: "We're always here when you need us.",

    ourProducts: "Our Products",
    ourProductsDesc: "Explore our key solutions: licensed BIM design software and modern antivirus tools to protect your devices and data.",
    viewAllProducts: "View All Products",

    reviewsTitle: "Trusted by Millions",
    review1_text: `"I completed training in BIM design for external networks. I'm very grateful for the practical approach and detailed explanation of each stage. Now I confidently apply the acquired knowledge in my work, and the training helped me reach a new level!"`,
    review1_name: "Alina Voronina",
    review1_role: "Design Engineer",

    review2_text: `"Thanks to the team, we moved the project from 2D to a full-fledged 3D BIM model. We got not only visualization but also real calculations for further work. Great support at every stage!"`,
    review2_name: "Igor Petrov",
    review2_role: "Architect",

    review3_text: `"This company is a true partner in information security. Thanks to their products, I feel confident about my data and device protection. I especially appreciate the transparency and the quick assistance from the sales team. Reliable service is what we need today!"`,
    review3_name: "Maxim Orlov",
    review3_role: "IT Director",

    ctaTitle: "Ready to Protect Your Digital World?",
    ctaText: "Join the secure digital world with SIT.",
    ctaBtnStart: "Get Started",
    ctaBtnContact: "Contact Sales",

    awardsTitle: "Awards and Achievements",
    awardsDesc: "Sklad Informatsionnykh Tekhnologiy is a leading provider of software for design and information modeling, as well as reliable cybersecurity products. The company is recognized with industry awards for implementing innovative BIM and data protection solutions.",
    award1: "Best Antivirus 2025",
    award2: "Top Security Provider",
    award3: "Customer Choice",
    award4: "Certified Protection",

    // Страница Продукты en
    productTitle: "Our Products",
    productDesc: "We offer licensed software for design, BIM modeling, and engineering tasks, as well as training courses for professionals.",
    searchPlaceholder: "Search products...",
    filters: "Filters",
    price: "Price (₸):",
    from: "From",
    to: "To",
    categories: "Categories:",
    cat1: "Autodesk",
    cat2: "Kaspersky Lab",
    cat3: "Data Protection",
    apply: "Apply",
    reset: "Reset Filters",
    more: "More",

    prod1desc: "Solution for infrastructure design.",
    prod2desc: "Architecture project validation.",
    prod3desc: "Protection for PCs, servers, and mobile devices.",
    prod4desc: "BIM for building designers and engineers.",
    prod5desc: "3D modeling, animation, and rendering.",
    prod6desc: "3D modeling for BIM projects and visualization.",

    // Страница Контакты en
    contactTitle: "Contact Us",
    contactDesc1: "If you have any questions about our products or services,",
    contactDesc2: "our team is always ready to help.",
    ourContacts: "Our Contacts",
    contactText: "We are here to help with any questions about our products, prices, or security solutions. Contact us by any of the means below and we will reply as soon as possible.",
    phone: "Phone",
    email: "Email",
    office: "Office",
    workTime: "Working Hours",
    socialTitle: "We are on social media",
    formTitle: "Send a Message",
    nameLabel: "Your Name *",
    phoneLabel: "Phone",
    emailLabel: "Email *",
    subjectLabel: "Subject *",
    subjectOption: "Select a subject",
    subject1: "Product Inquiry",
    subject2: "Technical Support",
    subject3: "Payment & Billing",
    subject4: "Partnership",
    subject5: "Other",
    messageLabel: "Message *",
    messagePlaceholder: "How can we help you?",
    agree: "I agree with the",
    policy: "privacy policy",
    sendBtn: "Send",
    thanksText: "Thank you, your message has been sent!",
    howFindUs: "How to find us",
    addressFooter: "16 Lugovaya St., Office 116, Pavlodar, Kazakhstan",
    workTime1: "Mon–Fri: 9:00 AM–6:00 PM",
    workTime2: "Mon–Fri: 09:00 AM–6:00 PM",
    weekend: "Sat–Sun: Closed",

    // Страница О нас en
    aboutTitle: "Warehouse of Information Technologies",
    aboutSubtitle: "14 YEARS OF RELIABILITY PROVEN BY TIME.",
    aboutHeader: "About Us",
    aboutDesc: "Warehouse of Information Technologies is a team of top-tier specialists with hands-on experience in BIM modeling and BIM implementation.",
    missionTitle: "Our Mission",
    missionDesc1: "We are an authorized Autodesk solution provider and BIM technology integrator, offering professional training for designers, BIM managers, and executives.",
    missionDesc2: "We provide not just products, but comprehensive solutions in:",
    missionPoint1: "1. Implementation of innovative design tools.",
    missionPoint2: "2. Information security.",
    missionPoint3: "3. Antivirus protection.",
    missionPoint4: "4. Solving non-standard IT tasks.",
    valuesTitle: "Our Core Values",
    valuesDesc: "The principles that drive our work at SIT.",
    value1: "Security Without Compromise",
    value1desc: "We never compromise on security. Our solutions offer multilayered protection from all types of threats.",
    value2: "Customers First",
    value2desc: "We design products based on user needs, making cybersecurity accessible and easy for everyone.",
    value3: "Continuous Innovation",
    value3desc: "Threats evolve — and so do we. We invest in R&D to stay ahead.",
    value4: "Global Perspective",
    value4desc: "With teams worldwide, we tackle cybersecurity issues relevant to different regions.",
    value5: "Striving for Excellence",
    value5desc: "We maintain the highest standards — from product development to customer support.",
    value6: "Education and Training",
    value6desc: "We believe in knowledge and work to spread cyber literacy.",
    teamTitle: "Our Team",
    teamDesc: "Meet the professionals behind our company’s success.",
    journeyTitle: "Our Journey",
    journeyDesc: "Since our founding, we’ve been committed to advancing digital security.",
    year2011: "Start",
    year2011desc: "Founded by a team of cybersecurity experts.",
    year2013: "Expansion",
    year2013desc: "Launched mobile protection and opened the first international office in Pavlodar.",
    year2016: "Innovation Award",
    year2016desc: "Our AI-based tech won a global innovation award; we reached 5M users worldwide.",
    year2019: "Global Presence",
    year2019desc: "Opened offices in Tokyo, Singapore, São Paulo — presence in 12 countries.",
    year2022: "Business Solutions",
    year2022desc: "Launched a corporate protection platform for businesses of all sizes.",
    year2025: "Today",
    year2025desc: "Protecting over 20 million users with AI-powered security solutions.",
    ctaTitle: "Join Our Mission to Protect the Digital World",
    ctaDesc: "Experience peace of mind with solutions trusted by millions.",
    ctaProductBtn: "Explore Products",
    ctaContactBtn: "Contact Us",

    // Футер en
    footerCompanyDesc: "Warehouse of Information Technologies — your reliable partner in cybersecurity.",
    footerProductsTitle: "Our Products",
    footerWorkTitle: "Working Hours",
    footerContactTitle: "Contacts",
    footerProduct1: "Autodesk",
    footerProduct2: "Kaspersky Lab",
    footerProduct3: "Training Courses",
    footerProduct4: "System Optimization",
    footerProduct5: "Secure Browser",
    footerWorkMon: "Monday: 09:00–18:00 (lunch 13:00–14:00)",
    footerWorkTue: "Tuesday: 09:00–18:00 (lunch 13:00–14:00)",
    footerWorkWed: "Wednesday: 09:00–18:00 (lunch 13:00–14:00)",
    footerWorkThu: "Thursday: 09:00–18:00 (lunch 13:00–14:00)",
    footerWorkFri: "Friday: 09:00–18:00 (lunch 13:00–14:00)",
    footerWorkSat: "Saturday: Closed",
    footerWorkSun: "Sunday: Closed",
    footerAddress: "Lugovaya, 16, Office 116, Pavlodar, Kazakhstan",
    footerCopyright: "© 2025 LLP Warehouse of Information Technologies. All rights reserved."
  },

  kz: {
// Шапка kz
    homehed: "Басты бет",
    producthed: "Өнімдер",
    contacthed: "Байланыс",
    abouthed: "Біз туралы",
    contactcallhed: "Бізбен байланысу",
// Страница Главная kz
    heroTitle: "АҚПАРАТТЫҚ ТЕХНОЛОГИЯЛАР ҚОЙМАСЫ",
    heroText: "Жобалау, BIM-модельдеу және ақпараттық қауіпсіздік саласындағы мамандар тобы. Модельдеу және антивирустық лицензияланған бағдарламаларды ұсынамыз, орнатуға, оқытуға көмектесеміз және клиенттерді қолдаймыз.",
    heroBtnProducts: "Біздің өнімдер",
    heroBtnLearnMore: "Толығырақ",

    whyChooseUs: "Неліктен СИТ таңдайды?",
    whyChooseDesc: "Біздің шешімдер сенімді қорғаныс пен жоғары өнімділікті қамтамасыз етеді.",
    advantage1: "Қазіргі заманғы қорғаныс",
    advantage1Desc: "Вирустардан, бопсалаушы бағдарламалардан және нөлдік күн қауіптерінен қорғайды.",
    advantage2: "Жылдам жұмыс",
    advantage2Desc: "Жүйеге төмен жүктеме, жоғары тиімділік.",
    advantage3: "Құпиялылық",
    advantage3Desc: "Сіздің деректеріңіз әрқашан қорғалған.",
    advantage4: "Тәулік бойы қолдау",
    advantage4Desc: "Сізге қажет кезде біз әрқашан жанымызда боламыз.",

    ourProducts: "Біздің өнімдер",
    ourProductsDesc: "BIM жобалау және модельдеу үшін лицензияланған бағдарламалармен, заманауи антивирустық шешімдермен танысыңыз.",
    viewAllProducts: "Барлық өнімдерді көру",

    reviewsTitle: "Миллиондардың сенімі",
    review1_text: `"Сыртқы желілердің BIM-жобалау бойынша оқудан өттім. Әр кезеңді егжей-тегжейлі түсіндіріп, тәжірибеге негізделген тәсіл үшін алғысым шексіз. Енді алған білімімді жұмыста сенімді қолдана аламын. Бұл оқу мені жаңа деңгейге көтерді!"`,
    review1_name: "Алина Воронина",
    review1_role: "Жобалау инженері",

    review2_text: `"Команданың арқасында жобамызды 2D-ден толыққанды 3D BIM-модельге көшіруге қол жеткіздік. Тек визуализация ғана емес, әрі қарайғы жұмысқа арналған нақты есептеулер де алдық. Әр кезеңде тамаша қолдау болды!"`,
    review2_name: "Игорь Петров",
    review2_role: "Архитектор",

    review3_text: `"Бұл компания – ақпараттық қауіпсіздік саласындағы нағыз серіктес. Олардың өнімдерінің арқасында деректер мен құрылғыларымның қорғалуына сенімдімін. Әсіресе, жұмыс процесінің ашықтығы мен сату бөлімінің жедел көмегі ұнайды. Қазіргі заманда сенімді сервис қажет!"`,
    review3_name: "Максим Орлов",
    review3_role: "IT-директор",

    ctaTitle: "Сандық әлеміңізді қорғауға дайынсыз ба?",
    ctaText: "СИТ-пен бірге сенімді цифрлық әлемге қосылыңыз.",
    ctaBtnStart: "Бастау",
    ctaBtnContact: "Сату бөліміне хабарласу",

    awardsTitle: "Марапаттар мен жетістіктер",
    awardsDesc: "СИТ — BIM және ақпараттық қауіпсіздік саласындағы жетекші шешімдер провайдері. Компания BIM және деректерді қорғау бойынша инновациялық шешімдер үшін салалық марапаттарға ие болды.",
    award1: "2025 жылдың үздік антивирусы",
    award2: "Қауіпсіздік бойынша үздік провайдер",
    award3: "Клиенттердің таңдауы",
    award4: "Сертификатталған қорғаныс",

    // Страница Продукты kz
    productTitle: "Біздің өнімдер",
    productDesc: "Жобалау, BIM-модельдеу және инженерлік тапсырмаларға арналған лицензияланған бағдарламалар мен мамандарға арналған оқу курстарын ұсынамыз.",
    searchPlaceholder: "Өнімдерді іздеу...",
    filters: "Сүзгілер",
    price: "Бағасы (₸):",
    from: "Бастап",
    to: "Дейін",
    categories: "Санаттар:",
    cat1: "Autodesk",
    cat2: "Kaspersky Lab",
    cat3: "Деректерді қорғау",
    apply: "Қолдану",
    reset: "Сүзгіні тазарту",
    more: "Толығырақ",

    prod1desc: "Инфрақұрылым нысандарын жобалау шешімі.",
    prod2desc: "Сәулеттік жобаларды тексеру.",
    prod3desc: "ДК, серверлер мен мобильді құрылғыларды қорғау.",
    prod4desc: "Ғимарат жобалаушылар мен инженерлерге арналған BIM.",
    prod5desc: "3D-модельдеу, анимация және рендеринг.",
    prod6desc: "BIM жобалары мен визуализацияға арналған 3D модельдеу.",

    // Страница Контакты kz
    contactTitle: "Бізбен байланысыңыз",
    contactDesc1: "Егер сізде өнімдер немесе қызметтер туралы сұрақтар болса,",
    contactDesc2: "біздің команда әрқашан көмектесуге дайын.",
    ourContacts: "Біздің байланыстар",
    contactText: "Өнімдеріміз, бағаларымыз немесе қауіпсіздік шешімдері туралы кез келген сұрақтарыңыз бойынша көмектесуге дайынбыз. Бізбен төмендегі тәсілдердің кез келгені арқылы хабарласыңыз, және біз тезірек жауап береміз.",
    phone: "Телефон",
    email: "Электрондық пошта",
    office: "Кеңсе",
    workTime: "Жұмыс уақыты",
    socialTitle: "Біз әлеуметтік желілерде",
    formTitle: "Хабарлама жіберу",
    nameLabel: "Сіздің атыңыз *",
    phoneLabel: "Телефон",
    emailLabel: "Эл. пошта *",
    subjectLabel: "Тақырып *",
    subjectOption: "Тақырыпты таңдаңыз",
    subject1: "Өнім туралы сұрақ",
    subject2: "Техникалық қолдау",
    subject3: "Төлем және шот",
    subject4: "Серіктестік",
    subject5: "Басқа",
    messageLabel: "Хабарлама *",
    messagePlaceholder: "Сізге қалай көмектесе аламыз?",
    agree: "Мен келісемін",
    policy: "құпиялылық саясатына",
    sendBtn: "Жіберу",
    thanksText: "Рахмет, сіздің сұранысыңыз жіберілді!",
    howFindUs: "Бізді қалай табуға болады",
    addressFooter: "Луговая көшесі, 16, кеңсе 116, Павлодар, Қазақстан",
    workTime1: "Дс–Жм: 9:00–18:00",
    workTime2: "Дс–Жм: 09:00–18:00",
    weekend: "Сб–Жс: Демалыс күндері",

    // Страница О нас kz
    aboutTitle: "Ақпараттық технологиялар қоймасы",
    aboutSubtitle: "14 ЖЫЛДЫҚ УАҚЫТТЫ ТЕКСЕРГЕН СЕНІМДІЛІК.",
    aboutHeader: "Біз туралы",
    aboutDesc: "Ақпараттық технологиялар қоймасы — BIM-модельдеу және енгізу саласында тәжірибесі мол мамандар тобы.",
    missionTitle: "Біздің миссиямыз",
    missionDesc1: "Autodesk шешімдерінің авторизацияланған жеткізушісі және BIM технологияларының интеграторы ретінде BIM саласында жобалаушыларға, BIM-менеджерлерге және басшыларға арналған кәсіби оқыту ұсынамыз.",
    missionDesc2: "Біз клиенттерімізге тек өнім емес, кешенді шешімдер ұсынамыз:",
    missionPoint1: "1. Инновациялық жобалау құралдарын енгізу.",
    missionPoint2: "2. Ақпараттық қауіпсіздік.",
    missionPoint3: "3. Антивирустық қорғаныс.",
    missionPoint4: "4. Ерекше IT тапсырмаларды шешу.",
    valuesTitle: "Негізгі құндылықтарымыз",
    valuesDesc: "СИТ компаниясындағы жұмысымыздың негізіндегі қағидалар.",
    value1: "Қауіпсіздік — ымырасыз",
    value1desc: "Қауіпсіздік — басты қағида. Көп деңгейлі қорғау жүйелерін ұсынамыз.",
    value2: "Клиент — басты назарда",
    value2desc: "Өнімдерімізді пайдаланушылардың қажеттілігіне қарай жасаймыз.",
    value3: "Үздіксіз инновация",
    value3desc: "Қауіптер дамиды — біз де дамимыз. ҒЗТКЖ-ға қаржы саламыз.",
    value4: "Жаһандық көзқарас",
    value4desc: "Әлемнің түкпір-түкпіріндегі командаларымыз әр аймаққа лайық шешімдер ұсынады.",
    value5: "Жоғары стандарттар",
    value5desc: "Жоғары сапа — өнімнен бастап қызметке дейін басты қағидатымыз.",
    value6: "Білім мен оқыту",
    value6desc: "Білімнің маңызы зор деп сенеміз және оны кеңінен таратамыз.",
    teamTitle: "Біздің команда",
    teamDesc: "Компания жетістігінің артында тұрған кәсіби мамандармен танысыңыз.",
    journeyTitle: "Біздің жолымыз",
    journeyDesc: "Құрылған сәттен бастап цифрлық қауіпсіздікті дамытуға арнадық.",
    year2011: "Бастау",
    year2011desc: "Қауіпсіздік саласындағы сарапшылар құрған.",
    year2013: "Кеңею",
    year2013desc: "Мобильді қорғау жүйесі іске қосылды, Павлодарда кеңсе ашылды.",
    year2016: "Инновация марапаты",
    year2016desc: "AI-технологиямыз қауіпсіздік саласында әлемдік марапат алды. 5 млн қолданушы.",
    year2019: "Халықаралық қатысу",
    year2019desc: "Токио, Сингапур, Сан-Паулу кеңселері — 12 елде қызмет көрсетеміз.",
    year2022: "Бизнес шешімдер",
    year2022desc: "Кәсіптерге арналған қауіпсіздік платформасын іске қостық.",
    year2025: "Бүгінгі күн",
    year2025desc: "20 млн+ қолданушыны қорғап отырмыз. AI және машиналық оқыту қолданылады.",
    ctaTitle: "Цифрлық әлемді қорғау миссиясына қосылыңыз",
    ctaDesc: "Миллиондаған адамдар сенетін шешімдермен тыныш өмір сүріңіз.",
    ctaProductBtn: "Өнімдерді қарау",
    ctaContactBtn: "Байланысу",

    // Футер kz
    footerCompanyDesc: "Ақпараттық технологиялар қоймасы — ақпараттық қауіпсіздік саласындағы сенімді серіктесіңіз.",
    footerProductsTitle: "Біздің өнімдер",
    footerWorkTitle: "Жұмыс уақыты",
    footerContactTitle: "Байланыс",
    footerProduct1: "Autodesk",
    footerProduct2: "Kaspersky Lab",
    footerProduct3: "Оқу курстары",
    footerProduct4: "Жүйені оңтайландыру",
    footerProduct5: "Қорғалған браузер",
    footerWorkMon: "Дүйсенбі: 09:00–18:00 (түскі ас 13:00–14:00)",
    footerWorkTue: "Сейсенбі: 09:00–18:00 (түскі ас 13:00–14:00)",
    footerWorkWed: "Сәрсенбі: 09:00–18:00 (түскі ас 13:00–14:00)",
    footerWorkThu: "Бейсенбі: 09:00–18:00 (түскі ас 13:00–14:00)",
    footerWorkFri: "Жұма: 09:00–18:00 (түскі ас 13:00–14:00)",
    footerWorkSat: "Сенбі: Демалыс",
    footerWorkSun: "Жексенбі: Демалыс",
    footerAddress: "Луговая, 16, 116-кеңсе, Павлодар, Қазақстан",
    footerCopyright: "© 2025 «Ақпараттық Технологиялар Қоймасы» ЖШС. Барлық құқықтар қорғалған."
  }
};
function setLanguage(lang) {
  localStorage.setItem('lang', lang);
  changeLanguage(lang);
}

function changeLanguage(lang) {
  const langData = translations[lang];
  if (!langData) return;

  for (const key in langData) {
    const el = document.getElementById(key);
    if (el) el.textContent = langData[key];
  }
}

// Привязка к кнопкам выбора языка
document.addEventListener('click', (e) => {
  if (e.target.dataset.lang) {
    setLanguage(e.target.dataset.lang);
  }
});

// Применяем язык при загрузке страницы
document.addEventListener('DOMContentLoaded', () => {
  const savedLang = localStorage.getItem('lang');
  if (savedLang) {
    changeLanguage(savedLang);
  }
});